"""Correlation-ID format validation.

Lives with auth because every authenticated request propagates a
correlation id, and the audit/log layer trusts the format this module
enforces.
"""

from __future__ import annotations

import re

_CORRELATION_ID_PATTERN = re.compile(
    r"^corr-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
)


def validate_correlation_id(correlation_id: str) -> bool:
    """Check that a correlation ID matches the expected format.

    Accepts the ``corr-{uuid4}`` format generated by the middleware
    or any string up to 128 characters (for externally provided IDs).
    """
    if not correlation_id or len(correlation_id) > 128:
        return False
    if correlation_id.startswith("corr-"):
        return bool(_CORRELATION_ID_PATTERN.match(correlation_id))
    # Allow external correlation IDs that are alphanumeric with dashes/underscores
    return bool(re.match(r"^[a-zA-Z0-9_-]{1,128}$", correlation_id))
