"""Mission command grammar.

Declarative specs for the verbs a player can type in the mission
console. The grammar is versioned data — parsers, help content, and
dispatchers all read from the same source of truth so adding a verb is
a single-file change.

Phase 3a ships the Blue-team verb set needed to complete scn-auth-001:
``alerts list`` / ``alerts show`` / ``correlate`` / ``contain session``,
plus the universal ``help`` / ``hint`` / ``status``. Red-team verbs
land in Phase 3b.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

Perspective = Literal["red", "blue", "both"]
FlagType = Literal["str", "int", "csv", "choice"]


@dataclass(frozen=True)
class FlagSpec:
    name: str
    type: FlagType = "str"
    required: bool = False
    default: object | None = None
    choices: tuple[str, ...] | None = None
    description: str = ""


@dataclass(frozen=True)
class PositionalSpec:
    name: str
    description: str = ""
    required: bool = True


@dataclass(frozen=True)
class VerbSpec:
    """A single verb in the grammar.

    ``name`` is always the first token. ``subcommand`` — when present —
    is the second token; together (name, subcommand) identifies the
    verb uniquely per perspective.
    """

    name: str
    subcommand: str | None = None
    handler: str = ""
    perspective: Perspective = "both"
    description: str = ""
    usage: str = ""
    positional: tuple[PositionalSpec, ...] = field(default_factory=tuple)
    flags: tuple[FlagSpec, ...] = field(default_factory=tuple)
    # Short one-line summary used in `help` output; defaults to the
    # first sentence of ``description`` if unset.
    summary: str = ""

    @property
    def key(self) -> str:
        return self.name if self.subcommand is None else f"{self.name} {self.subcommand}"

    def effective_summary(self) -> str:
        if self.summary:
            return self.summary
        if self.description:
            first_line, _, _ = self.description.partition("\n")
            return first_line
        return ""


# ---------------------------------------------------------------------------
# Universal verbs (both perspectives)
# ---------------------------------------------------------------------------


_UNIVERSAL_VERBS: tuple[VerbSpec, ...] = (
    VerbSpec(
        name="help",
        handler="help",
        perspective="both",
        usage="help [<verb>]",
        description=(
            "Show available verbs, or detailed usage for a specific verb. "
            "Free — no XP cost."
        ),
        positional=(PositionalSpec(name="verb", required=False),),
    ),
    VerbSpec(
        name="hint",
        handler="hint",
        perspective="both",
        usage="hint",
        description=(
            "Reveal the next recommended action for the current objective. "
            "Recruit: free. Analyst: -10 XP. Operator: -25 XP."
        ),
    ),
    VerbSpec(
        name="status",
        handler="status",
        perspective="both",
        usage="status",
        description=(
            "Show mission status, elapsed time, and objective progress."
        ),
    ),
)


# ---------------------------------------------------------------------------
# Blue team verbs (SOC analyst)
# ---------------------------------------------------------------------------


_BLUE_VERBS: tuple[VerbSpec, ...] = (
    VerbSpec(
        name="alerts",
        subcommand="list",
        handler="alerts.list",
        perspective="blue",
        usage="alerts list [--severity <low|medium|high|critical>]",
        description=(
            "List detection alerts generated by the current mission. "
            "Alerts are produced automatically as the adversary acts; "
            "this verb shows you what your SIEM has caught so far."
        ),
        flags=(
            FlagSpec(
                name="severity",
                type="choice",
                choices=("low", "medium", "high", "critical"),
                description="Filter by severity.",
            ),
        ),
    ),
    VerbSpec(
        name="alerts",
        subcommand="show",
        handler="alerts.show",
        perspective="blue",
        usage="alerts show <alert_id>",
        description="Show full detail for a specific alert, including the contributing events.",
        positional=(
            PositionalSpec(
                name="alert_id",
                description="The ID of the alert to show (e.g. AL-...).",
            ),
        ),
    ),
    VerbSpec(
        name="events",
        subcommand="tail",
        handler="events.tail",
        perspective="blue",
        usage="events tail [--last <n>] [--user <id>]",
        description=(
            "Tail the most recent events generated by this mission. "
            "Useful for confirming what the adversary is doing right now."
        ),
        flags=(
            FlagSpec(
                name="last",
                type="int",
                default=10,
                description="How many of the most recent events to show.",
            ),
            FlagSpec(
                name="user",
                type="str",
                description="Filter to events for a specific actor id (e.g. user-alice).",
            ),
        ),
    ),
    VerbSpec(
        name="correlate",
        handler="correlate",
        perspective="blue",
        usage="correlate [--alerts <id,id,...>]",
        description=(
            "Correlate alerts into an incident. If the detection "
            "pipeline has already auto-correlated, this verb confirms "
            "your decision and updates the incident note."
        ),
        flags=(
            FlagSpec(
                name="alerts",
                type="csv",
                description="Alert IDs to correlate (comma-separated).",
            ),
        ),
    ),
    VerbSpec(
        name="contain",
        subcommand="session",
        handler="contain.session",
        perspective="blue",
        usage="contain session --user <id> --action <revoke|stepup>",
        description=(
            "Contain an account under investigation. `revoke` kills "
            "every active session; `stepup` forces step-up auth on the "
            "next request. Either one satisfies the containment objective."
        ),
        flags=(
            FlagSpec(
                name="user",
                type="str",
                required=True,
                description="Actor id (e.g. user-alice).",
            ),
            FlagSpec(
                name="action",
                type="choice",
                choices=("revoke", "stepup"),
                required=True,
                description="Which containment action to apply.",
            ),
        ),
    ),
)


# ---------------------------------------------------------------------------
# Red team verbs — stub; full set lands in Phase 3b.
# ---------------------------------------------------------------------------


_RED_VERBS: tuple[VerbSpec, ...] = ()


# ---------------------------------------------------------------------------
# Public lookup
# ---------------------------------------------------------------------------


def verbs_for(perspective: Perspective) -> tuple[VerbSpec, ...]:
    """Return all verbs visible to ``perspective`` (universal + role)."""
    role_specific = _BLUE_VERBS if perspective == "blue" else _RED_VERBS
    return _UNIVERSAL_VERBS + role_specific


def find_verb(
    name: str, subcommand: str | None, perspective: Perspective
) -> VerbSpec | None:
    for v in verbs_for(perspective):
        if v.name == name and v.subcommand == subcommand:
            return v
    return None
