'use client';

interface AlertsHeaderProps {
  onRefresh: () => void;
}

export default function AlertsHeader({ onRefresh }: AlertsHeaderProps) {
  return (
    <section className="relative overflow-hidden rounded-2xl border border-slate-200 bg-gradient-to-br from-white via-rose-50 to-orange-50 px-6 py-8 shadow-sm dark:border-gray-800 dark:from-gray-900 dark:via-red-950/20 dark:to-gray-900">
      <div
        aria-hidden="true"
        className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-red-400/15 blur-3xl dark:bg-red-500/10"
      />
      <div className="relative flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <p className="text-[11px] font-mono uppercase tracking-[0.2em] text-red-700 dark:text-red-400">
            Detection Queue
          </p>
          <h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">
            Alerts
          </h1>
          <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600 dark:text-gray-400 sm:text-base">
            Review detections generated by the rule engine, triage by severity,
            and identify which alerts need deeper investigation or incident linkage.
          </p>
        </div>

        <button
          onClick={onRefresh}
          className="inline-flex items-center justify-center rounded-lg border border-slate-300 bg-white px-4 py-2 text-xs font-mono uppercase tracking-wide text-slate-700 transition-colors hover:bg-slate-100 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 dark:hover:bg-gray-800"
        >
          Refresh
        </button>
      </div>
    </section>
  );
}
